### PR TITLE
Set up a "Hello world" project with rails-react gem

### PR DESCRIPTION
**Pull request by ad9311**
### Greetings! 👋🏽 

In this PR I present my rails application using the react-rails gem.
Changes so far are:

- Implement a api with rails to get a random message everytime it's requested.
- Imeplement seeds.rb to populate message model. (Currently 5 messages).
- Static view and routing with reacr-router-dom
- Random button to get a random message.

**NOTE:** Keep in mind that since only 5 messages exists by the default, the chances of getting the same message are high.

My greeting component is named Message, I hope that's no trouble.

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
Hi, @ad9311 

Good job so far! 👏🏼 
- I liked the code structure and its implementation.

Great work on making the project requirements:clap:
You've done well implementing the project requirements, but there are still some issues which aren't been addressed yet 
 
## STATUS: CHANGES REQUESTED :recycle:


### Changes requested.
 - [ ] There is an issue while trying to render the root path as well as get a button in order to generate the random greetings
 
data-4
 
data-5

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by ad9311** [comment]
Following the required changes asked by the previous reviewer, I must say I wasn't able to reproduce the error he got. I aslo asked a peer to test my application but it worked for him just as fine as it did for me.

I have updated my README, please read it. There is a troubleshooting section there.

**Comment by ad9311** [comment]
app

**Review by Lameck1 — APPROVED** [review]
Hi, @ad9311,

This project is properly set with react-rails gem and all tasks properly implemented 💯.
Your project is therefore complete!  It's time to merge this branch:shipit: 

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
